#cloud-config
hostname: master

package_update: true
package_upgrade: true

packages:
  - containerd
  - apt-transport-https
  - ca-certificates
  - curl
  - gpg

write_files:
  # Apply sysctl params
  - path: /etc/sysctl.d/kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

runcmd:
  # Disable swap
  - swapoff -a
  - sed -i '/ swap / s/^/#/' /etc/fstab

  # Load K8s module
  - modprobe overlay
  - modprobe br_netfilter
  - sysctl --system

  # Default containerd config
  - mkdir -p /etc/containerd
  - sh -c 'containerd config default > /etc/containerd/config.toml'
  - sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
  - systemctl enable --now containerd
  - systemctl restart containerd

  # Add K8s repo
  - sh -c 'curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key > /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.asc'
  - sh -c 'echo "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /" > /etc/apt/sources.list.d/kubernetes.list'

  # Install K8s
  - apt-get update
  - apt-get install -y kubelet kubeadm kubectl
  - apt-mark hold kubelet kubeadm kubectl

  # Setup K8s master node
  - MASTER_IP=$(hostname -I | awk '{print $1}') && kubeadm init --apiserver-advertise-address=$MASTER_IP --pod-network-cidr=10.244.0.0/16
  - mkdir -p /home/ubuntu/.kube
  - cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
  - chown ubuntu:ubuntu /home/ubuntu/.kube/config
  - kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml

  # Add Helm
  - curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4
  - chmod 700 /tmp/get_helm.sh
  - bash /tmp/get_helm.sh
  - rm /tmp/get_helm.sh

  # Add ArgoCD
  # - kubectl --kubeconfig=/etc/kubernetes/admin.conf create namespace argocd
  # - kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -n argocd --server-side --force-conflicts -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
